apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-alertmanager-config
  namespace: ha-prom
data:
  values.yaml: |
    alertmanager:
      config:
        route:
          group_by: [ 'alertname']   # Groups alerts by namespace
          group_wait: 30s           # Time to wait before sending the first notification
          group_interval: 40s       # Minimum time between notifications for the same group
          repeat_interval: 12h      # Time to wait before re-sending notifications for the same alert
          receiver: 'email-config'  # Default receiver for all alerts
          routes:
          - receiver: 'email-config'  # Send matching alerts to the email receiver
            matchers: []
        receivers:
          - name: 'email-config'
            email_configs:
              - to: 'test@example.com'  # This is the email address that will receive the alert, captured by MailHog
                from: 'alertmanager@localhost'  # Sender email address
                smarthost: 'mailhog:1025'  # MailHog SMTP service running in Kubernetes
                require_tls: false  # MailHog does not require TLS
                headers:
                  subject: '[Alert] {{ .GroupLabels.alertname }} Replica: {{ range .Alerts }} Cluster: {{ .Labels.cluster }} {{ break }}{{ end }}'
                html: |
                  {{ range .Alerts }}
                      <b>Alert:</b> {{ .Labels.alertname }}<br>
                      <b>Severity:</b> {{ .Labels.severity }}<br>
                      <b>Cluster:</b> {{ .Labels.cluster }}<br>
                      <b>Details:</b> <pre>{{ .Annotations.description }}</pre><br><br>
                      {{ break }}  <!-- Stop after the first alert -->
                  {{ end }}

      alertmanagerSpec:
        replicas: 2

    prometheusOperator:
      admissionWebhooks:
        deployment:
          replicas: 2

    prometheus:
      promerheusSpec:
        externalLabels:
          replica: "prometheus-replica-$(POD_NAME)"
          cluster: "$(POD_NAME)"
        replicas: 2
      
        additionalAlertRelabelConfigs:
        - source_labels: [replica]
          regex: (.+)\d+
          target_label: replica
