apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
  namespace: loki
spec:
  releaseName: loki
  interval: 1h
  chart:
    spec:
      chart: loki
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
      version: 6.10.0 
  valuesFrom:
    - kind: ConfigMap
      name: loki-values
