apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: loki-stack
  namespace: loki
spec:
  interval: 10m
  path: "."
  prune: true
  resources:
    - helm-repo.yaml
    - configmap.yaml
    - helmrelease.yaml
