---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: loki-test
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./apps/loki-test
  prune: true
  sourceRef:
    kind: GitRepository
    name: loki-test
